import { type AssignmentData } from "@/components/assignments/AssignmentPageCard";

// Домашние задания потока. Отдельным модулем, потому что нужны и разделу ДЗ,
// и поиску: пока список был копией внутри страницы, поиск показывал задания
// прошлого потока после смены программы.
//
// Даты и публикация приходят из cohort_assignment_schedule и перекрывают
// поле deadline. Здесь — содержание: что сдать, по каким критериям.
export const PROGRAM_ASSIGNMENTS: AssignmentData[] = [
  {
    id: 1,
    hwNumber: 1,
    title: "Сводка через Cowork + своя рутина по формуле",
    lessonId: 1,
    lessonTitle: "Урок 1 · Что такое вайб кодинг + лестница автономии",
    deadline: "13.08.2026",
    status: "not_started",
    points: 50,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Сделать сводку через Cowork на общих данных в папке svodka/ и описать свою рабочую рутину промптом по формуле Сцена + Задача + Правила. Промпт показать в общем чате потока.",
    requirements: [
      "Развернуть Cowork: поставить, авторизоваться, проверить что всё работает",
      "Получить файл сводки в общей папке svodka/",
      "Приложить скрин или запись экрана с результатом",
      "Написать промпт под свою рутину по формуле Сцена + Задача + Правила",
      "Выложить промпт в общий чат и получить отклик от двух участников",
    ],
    checklist: [
      { id: 1, text: "Развернул Cowork и авторизовался", done: false },
      { id: 2, text: "Сводка по общим данным получена", done: false },
      { id: 3, text: "Подготовил скрин или запись экрана", done: false },
      { id: 4, text: "Написал промпт под свою рутину по формуле", done: false },
      { id: 5, text: "Промпт выложен в чат, двое откликнулись", done: false },
    ],
    feedback: null,
  },
  {
    id: 2,
    hwNumber: 2,
    title: "Рабочий сетап — семь галочек",
    lessonId: 3,
    lessonTitle: "Урок 3 · Личный контекст и первый проект",
    deadline: "15.08.2026",
    status: "not_started",
    points: 50,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Собрать систему, в которой вы делаете проекты и переключаете модели. Семь пунктов, каждый проверяется скриншотом: либо есть, либо нет. Почти всё делается в эфире на Лайвах 2 и 3, дома остаётся добить хвосты.\n\nПункт про git и первый коммит снят: на занятиях недели мы до него не дошли, разберём git и GitHub отдельно. Сдавать его не нужно.\n\nОтдельно про глобальный CLAUDE.md — файл ~/.claude/CLAUDE.md, который агент читает в каждой сессии. Возьмите скелет из материалов задания, удалите подсказки и заполните пять разделов под себя: кто вы и как с вами работать, что уже есть на вашей машине, где лежат проекты, правила работы и короткий стоп-лист. Критерий один: конкретика вместо общих слов. «Работаю с клиентами» не считается, «веду 12 клиентов в e-commerce, площадки Ozon и WB» считается. Держите файл коротким — 300-500 токенов, он стоит контекста в каждой сессии.",
    requirements: [
      "Скрин структуры папок: отдельная папка под проекты, в ~/.claude проектов нет",
      "Скрин settings.json",
      "Скрин переключения модели на живой задаче",
      "Скрин своего ~/.claude/CLAUDE.md: пять разделов, заполненных под себя",
      "Скрин первого проекта со своим CLAUDE.md внутри",
    ],
    checklist: [
      { id: 1, text: "Claude Code стартует из терминала внутри VS Code", done: false },
      { id: 2, text: "Заведена папка Claude Projects, проекты лежат только там", done: false },
      { id: 3, text: "В служебной ~/.claude проектов нет", done: false },
      { id: 4, text: "settings.json настроен: модель, effort, список моделей", done: false },
      { id: 5, text: "Переключение модели проверено на живой задаче, разница видна", done: false },
      { id: 6, text: "Глобальный ~/.claude/CLAUDE.md собран по скелету, пять разделов", done: false },
      { id: 7, text: "Первый проект создан в правильном месте, в нём свой CLAUDE.md", done: false },
    ],
    feedback: null,
  },
  {
    id: 3,
    hwNumber: 3,
    title: "Своё приложение на API + проект на GitHub",
    lessonId: 5,
    lessonTitle: "Урок 5 · Git и GitHub: совместная работа над проектом",
    deadline: "25.08.2026",
    status: "not_started",
    points: 60,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Два блока за неделю. Первый — своё приложение для работы с текстом через API модели, по мотивам разбора у Паши во вторник: программа берёт текст, прогоняет через модель и отдаёт результат. Провайдер любой — Claude API, OpenAI или другой, язык интерфейса тоже любой. Совет с занятия: сразу делайте приложение, а не автоматизацию, и сначала версию для себя — мультипользовательской её можно сделать потом.\n\nВторой — проект в git и на GitHub, с четверга. Главное здесь не количество коммитов, а то, что ключ от API лежит в .env и закрыт .gitignore, а не уезжает в репозиторий вместе с кодом.",
    requirements: [
      "Своё приложение для работы с текстом через Claude API или OpenAI, на любом языке",
      "Ссылка на репозиторий проекта на GitHub",
      "Скрин .gitignore: видно, что .env и секреты закрыты",
    ],
    checklist: [
      { id: 1, text: "Приложение работает: текст на входе, обработанный моделью на выходе", done: false },
      { id: 2, text: "Ключ от API лежит в .env, а не в коде", done: false },
      { id: 3, text: "Проект выложен на GitHub, в репозитории есть история коммитов", done: false },
      { id: 4, text: "В .gitignore закрыты .env и всё чувствительное", done: false },
      { id: 5, text: "Проверено, что в репозитории нет ключей", done: false },
    ],
    feedback: null,
  },
  {
    id: 4,
    hwNumber: 4,
    title: "MCP к своей системе + база знаний",
    lessonId: 7,
    lessonTitle: "Урок 7 · Память агента: четыре уровня",
    deadline: "01.09.2026",
    status: "locked",
    points: 70,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Подключить агента к своим источникам и выбрать уровень памяти под задачу по правилу «поднимайся когда упёрся».",
    requirements: [
      "Скрин работающего MCP на своих данных",
      "Описание, какой уровень памяти выбран и почему",
    ],
    checklist: [
      { id: 1, text: "MCP подключён и делает запросы к своей системе", done: false },
      { id: 2, text: "Права проверены, лишнего доступа нет", done: false },
      { id: 3, text: "База знаний подключена", done: false },
      { id: 4, text: "Выбор уровня памяти объяснён", done: false },
      { id: 5, text: "Дано peer review в общем чате", done: false },
    ],
    feedback: null,
  },
  {
    id: 5,
    hwNumber: 5,
    title: "Защищённый агент + зафиксированный кейс",
    lessonId: 9,
    lessonTitle: "Урок 9 · Свой кейс: выбор и запуск",
    deadline: "08.09.2026",
    status: "locked",
    points: 80,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Ограничить права агента двумя хуками и публично зафиксировать задачу, которая станет финальным проектом.",
    requirements: [
      "Два хука установлены и проверены: rm -rf блокируется",
      "Публично зафиксированный кейс в чате",
    ],
    checklist: [
      { id: 1, text: "Хук guard установлен, опасная команда блокируется", done: false },
      { id: 2, text: "Хук log установлен и пишет", done: false },
      { id: 3, text: "Security audit пройден", done: false },
      { id: 4, text: "Кейс назван в общем чате", done: false },
    ],
    feedback: null,
  },
  {
    id: 6,
    hwNumber: 6,
    title: "Рабочий кейс на своих данных",
    lessonId: 10,
    lessonTitle: "Урок 10 · Свой кейс: доведение до результата",
    deadline: "15.09.2026",
    status: "locked",
    points: 100,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Довести зафиксированный кейс до измеримого результата. Это ядро финального демо.",
    requirements: [
      "Ссылка на git-репозиторий",
      "Видео 2–3 минуты",
      "Артефакт результата: отчёт, контент, лиды",
    ],
    checklist: [
      { id: 1, text: "Кейс работает на собственных данных, не на учебных", done: false },
      { id: 2, text: "Есть видимый результат", done: false },
      { id: 3, text: "Видео снято", done: false },
      { id: 4, text: "Дано peer review двум участникам потока", done: false },
    ],
    feedback: null,
  },
  {
    id: 7,
    hwNumber: 7,
    title: "Финальный проект и защита",
    lessonId: 12,
    lessonTitle: "Урок 12 · Demo Day · Защита проектов",
    deadline: "15.09.2026",
    status: "locked",
    points: 120,
    pointsEarned: null,
    githubUrl: "",
    videoUrl: "",
    liveUrl: "",
    artifact: "",
    submittedAt: null,
    description:
      "Питч 5 минут на демо-дне плюс 3 минуты вопросов, рабочий проект за ним.",
    requirements: [
      "Питч 5 минут на демо-дне",
      "Рабочий проект",
      "Согласие на check-in через 30 дней",
    ],
    checklist: [
      { id: 1, text: "Питч собран по структуре: задача, решение, демо, результат", done: false },
      { id: 2, text: "Проект работает и показывается вживую", done: false },
      { id: 3, text: "Занят слот демо-дня", done: false },
      { id: 4, text: "Дано согласие на check-in через 30 дней", done: false },
    ],
    feedback: null,
  },
];
